import { Tajawal } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const tajawal = Tajawal({
//   subsets: ["arabic"],
//   weight: ["400", "700","900"], // choose weights you need
//   variable: "--font-tajawal", // ⬅️ important for custom Tailwind class
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className="font-serif">
        <Navbar />
      <main className=" ">{children}</main>
         <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={true}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
      />  
      </body>
    </html>
  );
}


//npm install date-fns --legacy-peer-deps